ENTITIES = [
    'person',
    'AI models',
    'datasets',
    'events',
    'AI researchers',
    'AI capabilities',
    'research papers',
    'technical metrics',
    'technical concepts',
    'evaluation tasks',
    'neural network components',
    'biological analogy',
    'time scales',
    'human brain components',
    'brain function',
    'memory systems',
    'neural imaging techniques',
    'cognitive processes',
    'biological systems',
    'medical conditions',
    'information representation',
    'learning processes',
    'intelligence concepts',
    'model training components',
    'business entities',
    'financial metrics',
    'compute resources',
    'research fields',
    'research concepts',
    'research programs',
    'research processes',
    'research bottleneck',
    'research organization',
    'web frameworks',
]